
$(REF_CLUSTER_TABLE):
	@$(MAKE) make_set_clusters \
		SET_CLUSTER_DIR=$(REF_CLUSTER_DIR) \
		SET_CLUSTER_INPUT_MATRIX=$(GENOME_GENE_TABLE) \
		SET_CLUSTER_INPUT_FIELD=$(REF_CLUSTER_INPUT_FIELD) \
		SET_CLUSTER_INPUT_MAP=$(REF_CLUSTER_INPUT_MAP) \
		SET_CLUSTER_TABLE=$(REF_CLUSTER_TABLE) \
		SET_CLUSTER_PREFIX=r \
		SET_GENES_TABLE=$(GENOME_GENE_TABLE) \
		SET_CLUSTER_QSUB_DIR=$(REF_QSUB_MAP_DIR) \
		SET_SELF=T \
		SET_TITLE=reference
make_ref_cluster: $(REF_CLUSTER_TABLE)

make_ref_lookup:
	$(_R) $(_md)/R/ref_table.r ref.table \
		id.ifn=$(PWD)/$(DOWNLOAD_INPUT_TABLE) \
		ref.ifn=$(GENOME_CONTIG_TABLE) \
		cluster.ifn=$(REF_CLUSTER_TABLE) \
		ofn=$(REF_CLUSTER_LOOKUP)

plot_ref_cluster:
	@$(MAKE) plot_set_clusters \
		SET_CLUSTER_DIR=$(REF_CLUSTER_DIR) \
		SET_CLUSTER_INPUT_MATRIX=$(GENOME_GENE_TABLE) \
		SET_CLUSTER_INPUT_FIELD=$(REF_CLUSTER_INPUT_FIELD) \
		SET_CLUSTER_INPUT_MAP=$(REF_CLUSTER_INPUT_MAP) \
		SET_CLUSTER_TABLE=$(REF_CLUSTER_TABLE) \
		SET_GENES_TABLE=$(GENOME_GENE_TABLE) \
		SET_TITLE=reference \
		SET_CLUSTER_QSUB_DIR=$(REF_QSUB_MAP_DIR) \
		SET_SELF=T \
		SET_CLUSTER_FDIR=$(REF_CLUSTER_FDIR)

.PHONY: plot_ref_cluster
